---
gitHubLogin: "google-oss-robot"
gitHubToken: "/etc/github-token/oauth"
onCallAddress: "" # No one is oncall for this at the moment.
skipPullRequest: false
selfAssign: true # Commenting `/cc`, so that autobump PR is not assigned to anyone
gitHubOrg: "GoogleCloudPlatform"
gitHubRepo: "oss-test-infra"
remoteName: "oss-test-infra"
headBranchName: "autobump-oss-misc"
upstreamURLBase: "https://raw.githubusercontent.com/kubernetes/test-infra/master"
imageRegistryAuth: google
includedConfigPaths:
  - "prow/oss/cluster"
  - "prow/prowjobs"
  - ".prow"
targetVersion: "latest"
extraFiles:
  - "prow/oss/config.yaml"
prefixes: 
  - name: "k8s-staging-test-infra GCR images"
    prefix: "gcr.io/k8s-staging-test-infra"
    repo: "https://github.com/kubernetes/test-infra"
    summarise: true
    consistentImages: true
