presubmits:
  GoogleCloudPlatform/k8s-cloud-provider:
  - name: pull-k8s-cloud-provider-test
    branches:
    - master
    always_run: true         # Run for every PR, or only when requested.
    labels:
      preset-service-account: "true"
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240903-6a352c5344-master
        command:
        - make
        - --
        - all
