# YAML anchors for reference elsewhere.
# to view expanded yaml, run: `yq eval 'explode(.)' [file]`
prow_ignored:
- &config-sync-ci-job
  interval: 1h
  cluster: build-kpt-config-sync
  labels:
    preset-service-account: "true"
    preset-dind-enabled-memory: "true"
  decorate: true
  decoration_config:
    timeout: 2h
  extra_refs:
  - org: GoogleContainerTools
    repo: kpt-config-sync
    base_ref: main
  spec: &config-sync-ci-job-spec
    containers:
    - &config-sync-ci-container
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220708-6b0cfd300e-1.23
      command:
      - runner.sh
      env:
      - name: UID
        value: "10333"
      - name: GID
        value: "10333"
      - name: GKE_E2E_TIMEOUT
        value: 2h
      - name: GCP_PROJECT
        value: oss-prow-build-kpt-config-sync
      securityContext:
        privileged: true
      volumeMounts:
      - name: prober-cred
        mountPath: /etc/prober-gcp-service-account
        readOnly: true
      resources:
        requests:
          memory: "2Gi"
          cpu: "2000m"
    nodeSelector:
      # This job requires 8vCPUs or less, so it is "small".
      cloud.google.com/gke-nodepool: small-job-pool
    volumes:
    - name: prober-cred
      secret:
        secretName: nomos-prober-runner-gcp-client-key

periodics:
- <<: *config-sync-ci-job
  name: multi-repo-1-standard-stable
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group1
    testgrid-tab-name: standard-stable
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group1
      - 'GCP_CLUSTER=multi-repo-1-standard-stable'

- <<: *config-sync-ci-job
  name: multi-repo-1-standard-regular
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group1
    testgrid-tab-name: standard-regular
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group1
      - 'GCP_CLUSTER=multi-repo-1-standard-regular'

- <<: *config-sync-ci-job
  name: multi-repo-1-standard-rapid
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group1
    testgrid-tab-name: standard-rapid
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group1
      - 'GCP_CLUSTER=multi-repo-1-standard-rapid'

- <<: *config-sync-ci-job
  name: multi-repo-1-standard-rapid-latest
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group1
    testgrid-tab-name: standard-rapid-latest
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group1
      - 'GCP_CLUSTER=multi-repo-1-standard-rapid-latest'

- <<: *config-sync-ci-job
  name: multi-repo-1-autopilot-stable
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group1
    testgrid-tab-name: autopilot-stable
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group1
      - 'GCP_CLUSTER=multi-repo-1-autopilot-stable'

- <<: *config-sync-ci-job
  name: multi-repo-1-autopilot-regular
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group1
    testgrid-tab-name: autopilot-regular
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group1
      - 'GCP_CLUSTER=multi-repo-1-autopilot-regular'

- <<: *config-sync-ci-job
  name: multi-repo-1-autopilot-rapid
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group1
    testgrid-tab-name: autopilot-rapid
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group1
      - 'GCP_CLUSTER=multi-repo-1-autopilot-rapid'

- <<: *config-sync-ci-job
  name: multi-repo-1-autopilot-rapid-latest
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group1
    testgrid-tab-name: autopilot-rapid-latest
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group1
      - 'GCP_CLUSTER=multi-repo-1-autopilot-rapid-latest'

- <<: *config-sync-ci-job
  name: multi-repo-2-standard-stable
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group2
    testgrid-tab-name: standard-stable
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group2
      - 'GCP_CLUSTER=multi-repo-2-standard-stable'

- <<: *config-sync-ci-job
  name: multi-repo-2-standard-regular
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group2
    testgrid-tab-name: standard-regular
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group2
      - 'GCP_CLUSTER=multi-repo-2-standard-regular'

- <<: *config-sync-ci-job
  name: multi-repo-2-standard-rapid
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group2
    testgrid-tab-name: standard-rapid
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group2
      - 'GCP_CLUSTER=multi-repo-2-standard-rapid'

- <<: *config-sync-ci-job
  name: multi-repo-2-standard-rapid-latest
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group2
    testgrid-tab-name: standard-rapid-latest
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group2
      - 'GCP_CLUSTER=multi-repo-2-standard-rapid-latest'

- <<: *config-sync-ci-job
  name: multi-repo-2-autopilot-stable
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group2
    testgrid-tab-name: autopilot-stable
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group2
      - 'GCP_CLUSTER=multi-repo-2-autopilot-stable'

- <<: *config-sync-ci-job
  name: multi-repo-2-autopilot-regular
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group2
    testgrid-tab-name: autopilot-regular
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group2
      - 'GCP_CLUSTER=multi-repo-2-autopilot-regular'

- <<: *config-sync-ci-job
  name: multi-repo-2-autopilot-rapid
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group2
    testgrid-tab-name: autopilot-rapid
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group2
      - 'GCP_CLUSTER=multi-repo-2-autopilot-rapid'

- <<: *config-sync-ci-job
  name: multi-repo-2-autopilot-rapid-latest
  annotations:
    testgrid-dashboards: googleoss-kpt-config-sync-multi-repo-test-group2
    testgrid-tab-name: autopilot-rapid-latest
  spec:
    <<: *config-sync-ci-job-spec
    containers:
    - <<: *config-sync-ci-container
      args:
      - make
      - test-e2e-gke-multi-repo-test-group2
      - 'GCP_CLUSTER=multi-repo-2-autopilot-rapid-latest'
